name: CI

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: 'pip'

      - name: install
        run: |
          make install-linting
          pip freeze

      - name: run linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: true
          mypy: true
          mypy_args: pydantic_ssm_settings

  test-linux:
    name: test py${{ matrix.python-version }} on linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # python-version: ["3.6", "3.7", "3.8", "3.9"]
        python-version: ["3.8"]
    env:
      PYTHON: ${{ matrix.python-version }}
      OS: ubuntu

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install
        run: |
          make install-testing
          pip freeze
      
      - name: test uncompiled without deps
        run: make test
        env:
          COVERAGE_FILE: coverage/.coverage.linux-py${{ matrix.python-version }}-cN-dN
          CONTEXT: linux-py${{ matrix.python-version }}-compiled-no-deps-no

      - name: store coverage files
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
