name: Publish

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # You must set fetch-depth to 0 when using actions/checkout@v2, since
          # Python Semantic Release needs access to the full history to
          # determine whether a release should be made.
          fetch-depth: 0

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: "pip"

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.PYPI_API_TOKEN }}
